.gitattributes, .github/workflows/release.yml, README.md, styles.css
Inspired by [this](https://github.com/muness/obsidian-ics/issues/11) issue thread this is an update to clean up some unused code and make a small clarification on the README file.
=> Remove styles.css and update README

src/main.ts
I moved the event fetching to an own function returning an array of dicts.
Like this, it can be used with other plugins like Templater or Dataview. This is possibly a solution to #24.
This might also be used as preparation to solve #3 (replace formating forEach), #13 (getEvent already accepts an arbitrary date), #14 (I added the “description” field), #16.
Examples:
Dataview:
```dataviewjs
var events = await app.plugins.getPlugin('obsidian-ics').getEvents("2022-07-27");
var mdArray = [];
events.forEach((e) => {
mdArray.push(`${e.time} ${e.summary} ${e.location}: ${e.description}`.trim())
})
dv.list(dv.array(mdArray))
```
Templater:
<%
(async () => {
var events = await app.plugins.getPlugin('obsidian-ics').getEvents("2022-07-27");
var mdArray = [];
events.forEach((e) => {
mdArray.push(`- …
=> Export event getter function

manifest.json
Closes #45, tested on Android only
=> Allow plugin to run on mobile

package.json, src/icalUtils.ts, src/main.ts, src/settings/ICSSettingsTab.ts
=> Apply_feedback_from_community_submission_review

.github/workflows/release.yml
=> let's try to simplify this, based on https://github.com/Lewuathe/obsidian-mlir-syntax-highlight/blob/main/.github/workflows/release.yml

manifest.json, src/icalUtils.ts, src/main.ts, src/settings/ICSSettingsTab.ts, tsconfig.json
https://github.com/muness/obsidian-ics/issues/6#issuecomment-1656104196
=> Apply_feedback_from_community_submission_3

src/main.ts, src/settings/ICSSettings.ts, src/settings/ICSSettingsTab.ts
As described in #59, I'd like to include location in the output format
=> add location to the calendar settings

README.md, src/main.ts, src/settings/ICSSettings.ts, src/settings/ICSSettingsTab.ts
=> FR: Support checkboxes OR bullets #67

.github/FUNDING.yml, .github/release.yml, README.md, src/IEvent.ts, src/icalUtils.ts, src/main.ts
Address #14 by handling common types of meeting platforms and provide clickable links to join meetings directly from the generated markdown.
=> Extract meeting URL from event

src/icalUtils.ts
The goal is to reduce the bugs with errant and missing recurring events. By relying more on rrule, am hoping this will get rid of bugs introduced by my code.
Still have some missing events and maybe some TZ issues.
=> Simplify rrule parsing

src/main.ts, src/settings/ICSSettings.ts, src/settings/ICSSettingsTab.ts
=> Add data view syntax for event start and end

src/settings/ICSSettingsTab.ts
=> Fix settings modal bug and save plugin settings

.gitignore, package-lock.json, src/main.ts, src/settings/ICSSettings.ts, src/settings/ICSSettingsTab.ts
=> vdir support

src/icalUtils.ts
While exploring #98, I noticed that the first time a recurring event is showing up twice.
This PR is a fix for that issue.
=> Duplicate listing on the first recurrence of an event

package-lock.json, src/IEvent.ts, src/main.ts, src/settings/ICSSettings.ts, src/settings/ICSSettingsTab.ts
=> Adding attendees and their responses

src/main.ts
=> added graceful handling of non-daily note use

.github/workflows/release.yml, src/main.ts, src/settings/ICSSettingsTab.ts, styles.css
=> Settings modal improvements

src/icalUtils.ts, src/main.ts
=> Fix issues with event filtering

src/icalUtils.ts
=> [BUG] Regression with previous and next day events showing up

package-lock.json, src/icalUtils.ts, src/main.ts, src/settings/ICSSettings.ts, src/settings/ICSSettingsTab.ts
Add an optional owner email setting to skip declined events
=> Skip declined event for recurring events

package-lock.json, src/main.ts, src/settings/ICSSettings.ts, src/settings/ICSSettingsTab.ts
- Added a setting to show/hide transparent events in the calendar.
- Updated excludeTransparentEvents method to respect the new setting.
- Updated default calendar format to include showTransparentEvents option.
Fixes #140
=> Improve handling of transparent events

README.md
Add instructions for O365 calendars (ht @profmikegreene)
=> Add instructions to get Microsoft Office 365 calendar URL
